name: ulvinge.se
markdown: kramdown
highligther: pygments
timezone: GMT+1
exclude: ['Gemfile', 'Gemfile.lock', '*.sublime-*', 'lib','vendor', 'Rakefile', 's3_website.yml']
relative_permalinks: false
url: ulvinge.se
author: Niklas Ulvinge
gems:
    - jekyll-feed
sass:
  style: compressed
